INSERT INTO USER (USER_ID, PRINCIPAL, CREDENTIAL, NAME, ROLE ) VALUES (1, 'admin@b105.io', '{bcrypt}$2a$10$46kFNSAbcqXape3bPNaC7u.Yzng4n7pAMz1MZRYp43lnXmg91uNie', '동동스','ADMIN');
INSERT INTO USER (USER_ID, PRINCIPAL, CREDENTIAL, NAME, ROLE ) VALUES (2, 'supporter@b105.io', '{bcrypt}$2a$10$trNV9bcC4Nrp14raysXS7uINW9R1quVGX7MqF16fxp1xPehrPtwMe', '후원맨','SUPPORTER');
INSERT INTO USER (USER_ID, PRINCIPAL, CREDENTIAL, NAME, ROLE ) VALUES (3, 'shelter@b105.io', '{bcrypt}$2a$10$k3crd.DWjEaTJ7vi8luN4.GI.kWvnBAaO8fHBG.IJyClDq3MizIWa', '유기견보호소','SHELTER');


