INSERT INTO USER (USER_ID, PRINCIPAL, CREDENTIAL, NAME) VALUES (1, 'admin@b105.io', '{bcrypt}$2a$10$46kFNSAbcqXape3bPNaC7u.Yzng4n7pAMz1MZRYp43lnXmg91uNie', '동동스');
INSERT INTO USER (USER_ID, PRINCIPAL, CREDENTIAL, NAME) VALUES (2, 'supporter@b105.io', '{bcrypt}$2a$10$trNV9bcC4Nrp14raysXS7uINW9R1quVGX7MqF16fxp1xPehrPtwMe', '후원맨');
INSERT INTO USER (USER_ID, PRINCIPAL, CREDENTIAL, NAME) VALUES (3, 'shelter@b105.io', '{bcrypt}$2a$10$k3crd.DWjEaTJ7vi8luN4.GI.kWvnBAaO8fHBG.IJyClDq3MizIWa', '유기견보호소');

INSERT INTO AUTHORITY(AUTHORITY_ID,AUTHORITY,USER_ID) VALUES (1,'ADMIN',1);
INSERT INTO AUTHORITY(AUTHORITY_ID,AUTHORITY,USER_ID) VALUES (2,'SUPPORTER',2);
INSERT INTO AUTHORITY(AUTHORITY_ID,AUTHORITY,USER_ID) VALUES (3,'SHELTER',3);


