FROM openjdk:11 as builder

# Host의 디렉토리/파일을 도커 이미지의 파일 시스템에 복사하는 용도로 사용됩니다.
# 절대경로와 상대경로 모두 지원합니다. 상대경로를 사용할 경우 WORKDIR을 고려해야합니다.
COPY . .

# RUN 명령어는 Shell의 커맨드와 같습니다. 도커 이미지 빌드과정 중 필요한 명령어 실행을 위해 사용됩니다.
RUN ./gradlew clean build

FROM openjdk:11
COPY --from=builder /build/libs/*.jar app.jar

EXPOSE 8080
ENTRYPOINT [ "java", "-jar","./app.jar" ]
